<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>

<package format="3">

    <name>opendds_visualizer_plugin</name>
    <version>2.2.0</version>
    <description>OpenDDS Visualizer Plugin for PlotJuggler</description>

    <maintainer email="support@eProsima.comm">eProsima Support</maintainer>

    <license file="LICENSE">GPLv3</license>

    <url type="website">https://www.eprosima.com/</url>
    <url type="bugtracker">https://github.com/Airbotix-Technology-Pvt-Ltd/opendds-visualizer-plugin/issues</url>
    <url type="repository">https://github.com/Airbotix-Technology-Pvt-Ltd/opendds-visualizer-plugin</url>

    <author email="javierparis@eprosima.com">Javier Paris</author>

    <buildtool_depend>cmake</buildtool_depend>

    <!-- OpenDDS dependencies -->
    <depend>opendds</depend>

    <!-- Plotjuggler -->
    <depend>plotjuggler</depend>

    <!-- common dependancies -->
    <depend>qtbase5-dev</depend>
    <depend>binutils</depend>
    <depend>libqt5-svg-dev</depend>
    <depend>libqt5-websockets-dev</depend>
    <depend>boost</depend>

    <export>
        <build_type>cmake</build_type>
    </export>

</package>
