<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>

<package format="3">

    <name>opendds_visualizer_plugin</name>
    <version>0.0.0</version>
    <description> OpenDDS Visualizer Plugin for PlotJuggler</description>

    <maintainer email="business@airbotix.in">Airbotix Support</maintainer>

    <license file="LICENSE">GPLv3</license>

    <url type="website">https://airbotix.in/</url>
    <url type="bugtracker">https://github.com/Airbotix-Technology-Pvt-Ltd/opendds-visualizer-plugin/issues</url>
    <url type="repository">https://github.com/Airbotix-Technology-Pvt-Ltd/opendds-visualizer-plugin/</url>

    <author email="shubham.garg@airbotix.in">Shubham Garg</author>
    <author email="sumiy@airbotix.in">Sumit Bhardwaj</author>

    <buildtool_depend>cmake</buildtool_depend>

    <!-- OpenDDS dependencies -->
    <depend>OpenDDS</depend>
    <depend>OpenDDW</depend>

    <!-- Plotjuggler -->
    <depend>plotjuggler</depend>

    <!-- common dependancies -->
    <depend>qtbase5-dev</depend>
    <depend>binutils</depend>
    <depend>libqt5-svg-dev</depend>
    <depend>libqt5-websockets-dev</depend>
    <depend>boost</depend>

    <export>
        <build_type>cmake</build_type>
    </export>

</package>
