services:
  opendds-visualizer-plugin:
    build:
      context: .
      dockerfile: Dockerfile
    image: opendds-visualizer-plugin
    container_name: plotjuggler
    network_mode: host
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=${XAUTHORITY:-$HOME/.Xauthority}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority
    stdin_open: true
    tty: true
    # command: "bash" # uncomment for debuuging inside docker
    command: > # comment for debugging inside docker
      bash -c "source /DDS-Visualizer-Plugin/install/setup.bash &&
      plotjuggler -n --plugin_folders /DDS-Visualizer-Plugin/install/opendds_visualizer_plugin/bin/"